version: "2"
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: utjmovil
      MYSQL_USER: utjwebuser
      MYSQL_PASSWORD: Nov.2023$$
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: utjwebuser
      MYSQL_PASSWORD: Nov.2023$$
      MYSQL_ROOT_PASSWORD: test
    depends_on:
      - db
  api:
    build: ./utj
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  persistent:
